### ISSUE TITLE
Hungarian version cannot run the code

### ISSUE THREAD

**Issue by krajcsi** [AlgoTaurus/algotaurus#49]
Write some code, then try to run it by pressing F5.

The error message: 
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__
    return self.func(*args)
  File "algotaurus.py", line 717, in runmode
    self.execute_code()
  File "algotaurus.py", line 737, in execute_code
    self.labyrmenu.entryconfig("Type", state="disabled")
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2788, in entryconfigure
    return self._configure(('entryconfigure', index), cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1320, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
TclError: bad menu entry index "Type"

**Comment by krajcsi** [comment]
Regression was introduced in e85ed5440a18a244421d66c997525d7fcee358d9
Not sure why it does not work in the Hungarian version, but for some reason it gives the error message above.
This was accidentally fixed in pull request #39
